---
title: "PA1_template"
author: "Rosa Elisa Rodriguez Martinez"
date: "January 9, 2016"
output: html_document
---

```{r, echo=TRUE}
rm(list=ls(all=TRUE))
setwd("~/R/Coursera/Reproducible research")
Act <- read.csv("~/R/Coursera/Reproducible research/activity.csv")


#Transformations
Act$steps <- as.numeric(Act$steps)

#Remove NA
Act2<-na.omit(Act)

#What is mean total number of steps taken per day?

Steps<-aggregate(Act2$steps, list(Act2$date), sum)
mean(Steps$x) # The mean total number of steps taken per day is 10,766.19


# 1. Calculate the total number of steps taken per day 

Steps

# 2. Make a histogram of the total number of steps taken each day

library (ggplot2)
ggplot(data=Steps,aes(Group.1,x))+geom_histogram(stat="identity", fill="blue", colour="black")+
        xlab("Date")+ylab("Steps per day")+
        theme(axis.text.x = element_text(angle = 90, hjust = 1))


#3. Calculate and report the mean and median of the total number of steps taken per day
library(plyr)
Steps2<- ddply(Act, "date", summarise, mean = mean (steps), median = median(steps))
Steps2


#What is the average daily activity pattern?

# 1. Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) 
# and the average number of steps taken, averaged across all days (y-axis)

Steps3<- ddply(Act2, "interval", summarise, mean = mean(steps))

ggplot(Steps3, aes(interval, mean)) + geom_line() +
        xlab("Interval") + ylab("Average number of steps averaged across all days")+
        scale_x_continuous()


# 2. Which 5-minute interval, on average across all the days in the dataset, 
#contains the maximum number of steps?

library(plyr)
arrange(Steps3, desc(mean)) ## The maximum number of steps is found on interval 835 which in average had 206.17 steps

## Imputing missing values

#  1. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

summary(Act)        ## The number of missing values in the dataset is 2304


# 2. Devise a strategy for filling in all of the missing values in the dataset. 
#The strategy does not need to be sophisticated. For example, you could use 
#the mean/median for that day, or the mean for that 5-minute interval, etc.

impute.mean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE)) #replace NA with mean function

dat2 <- ddply(Act, ~ interval, transform, steps = impute.mean(steps)) # Replaces NA with the mean of each interval


# 3. Create a new dataset that is equal to the original dataset but with the missing data filled in.

dat3<-arrange(dat2, date, interval, steps) # reorder to have new datase equal as the original


# 4. Make a histogram of the total number of steps taken each day 

Steps4<-aggregate(dat3$steps, list(dat3$date), sum)
Steps4

ggplot(data=Steps4,aes(Group.1,x))+geom_histogram(stat="identity", fill="red", colour="black")+
        xlab("Date")+ylab("Steps per day")+
        theme(axis.text.x = element_text(angle = 90, hjust = 1))

# Calculate and report the mean and median total number of steps taken per day. 

Steps5<- ddply(dat3, "date", summarise, mean = mean (steps), median = median(steps))
Steps5

#Do these values differ from the estimates from the first part of the assignment?  #Yes the values differ as shown in chart

Steps6<- merge(x = Steps2, y = Steps5, by = "date", all = TRUE) # join the two datasets
str(Steps6)

library(reshape2) # for melt()
melt_Steps6 <- melt(Steps6)
head(melt_Steps6) # so you can see it

ggplot(data=melt_Steps6,aes(date,value))+geom_histogram(stat="identity")+facet_grid(variable~.)+
  xlab("Date")+ylab("Mean and median of steps per day (x = original, y = replaced NA")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))



#What is the impact of imputing missing data on the estimates of the total daily number of steps? 

# the number of steps per day increases in some days and there are less emply spaces on the dates

Steps7<- merge(x = Steps, y = Steps4, by = "Group.1", all = TRUE) 
str(Steps7)
melt_Steps7 <- melt(Steps7)

ggplot(data=melt_Steps7,aes(Group.1,value))+geom_histogram(stat="identity")+facet_grid(variable~.)+
        xlab("Date")+ylab("Total steps per day")+
        theme(axis.text.x = element_text(angle = 90, hjust = 1))


##Are there differences in activity patterns between weekdays and weekends?

# 1. Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.

Act$day <- weekdays(as.Date(Act$date))

library(timeDate)

dat3$day <- weekdays(as.Date(dat3$date)) #include the day of the week
dat3$IsWeekday<-isWeekday(dat3$date, wday=1:5) # True = weekday, False = weekend

dataPlot3<-aggregate(dat3[, 1], list(dat3$IsWeekday, dat3$interval), mean) # mean for each interval on weekday and weekend

str(dataPlot3)

#  Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) 
#and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). 
#See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.

#To change the facet label name

mf_labeller <- function(var, value){
  value <- as.character(value)
  if (var=="Group.1") { 
    value[value=="TRUE"] <- "Weekday"
    value[value=="FALSE"]   <- "Weekend"
  }
  return(value)
}

# time series plot of the average number of steps per interval across all weekday days and weekend days

ggplot(dataPlot3, aes(Group.2, x)) + geom_line() +facet_grid(Group.1~., labeller=mf_labeller)+
        xlab("Interval") + ylab("Average number of steps averaged across all days")

