---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r data}
activity <- read.csv("activity.csv",
                     colClasses = c("numeric", "Date", "numeric"),
                     na.strings = "NA")
```


## What is mean total number of steps taken per day?
```{r mean}
with(activity, hist(steps,
                    main = "Histogram of Total Number of Steps Taken Each Day",
                    xlab = "Number of Steps",
                    ylab = "Count"))
mean(activity$steps, na.rm = TRUE)
median(activity$steps, na.rm = TRUE)
```

## What is the average daily activity pattern?
```{r dailypattern}
meanStepsByInterval <- with(activity,
                            tapply(steps, interval, mean,
                                   na.rm = TRUE, simplify = TRUE))
plot(names(meanStepsByInterval),
     meanStepsByInterval, type = "l",
     main = "Average Number of Steps Taken by 5-minute Interval",
     xlab = "Interval Number",
     ylab = "Number of Steps Taken")
meanStepsByInterval[which.max(meanStepsByInterval)]
```

## Imputing missing values
```{r impute}
sum(is.na(activity$steps))
means <- data.frame(interval = names(meanStepsByInterval),
                    mean = meanStepsByInterval)
merged <- merge(activity, means)
merged <- transform(merged, steps = ifelse(is.na(steps), mean, steps))
activityNew <- with(merged, data.frame(merged[order(date, interval),
                                              c("steps", "date", "interval")],
                                       row.names = 1:nrow(activity)))
with(activityNew, hist(steps,
                       main = "Histogram of Total Number of Steps Taken Each Day",
                       xlab = "Number of Steps",
                       ylab = "Count"))
mean(activityNew$steps, na.rm = TRUE)
median(activityNew$steps, na.rm = TRUE)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r difference}
activityNew$week <- ifelse(weekdays(activityNew$date) %in% c("Saturday", "Sunday"),
                           "Weekend", "Weekday")
meanStepsByIntervalWeekday <- with(subset(activityNew, week == "Weekday"),
                                   tapply(steps, interval, mean, simplify = TRUE))
meanStepsByIntervalWeekend <- with(subset(activityNew, week == "Weekend"),
                                   tapply(steps, interval, mean, simplify = TRUE))
meansWeekday <- data.frame(interval = as.numeric(names(meanStepsByIntervalWeekday)),
                           mean = meanStepsByIntervalWeekday, week = "Weekday")
meansWeekend <- data.frame(interval = as.numeric(names(meanStepsByIntervalWeekend)),
                           mean = meanStepsByIntervalWeekend, week = "Weekend")
mergedMeans <- data.frame(rbind(meansWeekday, meansWeekend), row.names = 1:576)

library(lattice)
xyplot(mean ~ interval | week, layout = c(1, 2),
       data = mergedMeans, type = "l",
       main = "Activity Patterns between Weekdays and Weekends",
       xlab = "Interval Number",
       ylab = "Number of Steps Taken")
```